# config/services.yaml
services:
    zapsign_bundle.utils:
        class: ThomasSens\ZapsignBundle\Service\Utils
        public: true
        arguments: ['@logger']

    zapsign_bundle.zapsign_client:
        class: ThomasSens\ZapsignBundle\Service\ZapsignClient
        public: true
        arguments: ['@parameter_bag','@logger','@zapsign_bundle.utils']

